### ISSUE TITLE
window is not defined error

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuel-connectors#52]
### Summary

When building with the following code snippet, I get a `window is not defined` error.

```ts
export const fuelConfig: FuelConfig = {
  connectors: defaultConnectors({
    devMode: true,
  })
}
```

The error seems to reference this statement.
https://github.com/FuelLabs/fuel-connectors/blob/495d7d377a6419da4641bc1b65f71493732374f4/packages/evm-connector/src/EvmWalletConnector.ts#L71

### Expect

No error to be throw on build.

### Actual

The following error is thrown:

```console
ReferenceError: window is not defined
    at kr.configProviders (file:///.../fuels-ts/node_modules/.pnpm/@fuels+connectors@0.2.2_fuels@packages+fuels/node_modules/@fuels/connectors/dist/index.mjs:1:109435)
    at new kr (file:///.../fuels-ts/node_modules/.pnpm/@fuels+connectors@0.2.2_fuels@packages+fuels/node_modules/@fuels/connectors/dist/index.mjs:1:109228)
    at Wr (file:///.../fuels-ts/node_modules/.pnpm/@fuels+connectors@0.2.2_fuels@packages+fuels/node_modules/@fuels/connectors/dist/index.mjs:1:117849)
    at eval (webpack-internal:///./src/pages/_app.tsx:31:85)
ReferenceError: window is not defined
    at kr.configProviders (file:///.../fuels-ts/node_modules/.pnpm/@fuels+connectors@0.2.2_fuels@packages+fuels/node_modules/@fuels/connectors/dist/index.mjs:1:109435)
    at new kr (file:///.../fuels-ts/node_modules/.pnpm/@fuels+connectors@0.2.2_fuels@packages+fuels/node_modules/@fuels/connectors/dist/index.mjs:1:109228)
    at Wr (file:///.../fuels-ts/node_modules/.pnpm/@fuels+connectors@0.2.2_fuels@packages+fuels/node_modules/@fuels/connectors/dist/index.mjs:1:117849)
    at eval (webpack-internal:///./src/pages/_app.tsx:31:85)
 ⨯ unhandledRejection: ReferenceError: window is not defined
    at kr.configProviders (file:///.../fuels-ts/node_modules/.pnpm/@fuels+connectors@0.2.2_fuels@packages+fuels/node_modules/@fuels/connectors/dist/index.mjs:1:109435)
    at new kr (file:///.../fuels-ts/node_modules/.pnpm/@fuels+connectors@0.2.2_fuels@packages+fuels/node_modules/@fuels/connectors/dist/index.mjs:1:109228)
    at Wr (file:///.../fuels-ts/node_modules/.pnpm/@fuels+connectors@0.2.2_fuels@packages+fuels/node_modules/@fuels/connectors/dist/index.mjs:1:117849)
    at eval (webpack-internal:///./src/pages/_app.tsx:31:85)
 ⨯ unhandledRejection: ReferenceError: window is not defined
    at kr.configProviders (file:///.../fuels-ts/node_modules/.pnpm/@fuels+connectors@0.2.2_fuels@packages+fuels/node_modules/@fuels/connectors/dist/index.mjs:1:109435)
    at new kr (file:///.../fuels-ts/node_modules/.pnpm/@fuels+connectors@0.2.2_fuels@packages+fuels/node_modules/@fuels/connectors/dist/index.mjs:1:109228)
    at Wr (file:///.../fuels-ts/node_modules/.pnpm/@fuels+connectors@0.2.2_fuels@packages+fuels/node_modules/@fuels/connectors/dist/index.mjs:1:117849)
    at eval (webpack-internal:///./src/pages/_app.tsx:31:85)
```

**Comment by luizstacio** [comment]
@petertonysmith94 thanks for the report we fixed the issue on version 0.2.2, can you try and let me know if it works now?
